Verify redirections of warning (to stdout) and errors (to stderr). To simplify diagnostics, name of functions are add in errors messages and warnings.

diff --git a/genvm b/genvm
--- a/genvm
+++ b/genvm
@@ -48,6 +48,7 @@ SERVER="http://ftp.debian.org/debian"
 SIZE="5G"
 FORMAT="vmdk"
 MINIMAL_SIZE=500M
+ERROR_MINIMAL_SIZE=1M
 
 declare -a STEPS PARTSTABLE ORDER_TABLE MONTEDPARTS
 
@@ -149,10 +150,10 @@ find_loop () {
 	_LOOP=$(losetup -f)
 	[ -z "${_LOOP}" ] && {
 		${CALL_BACK} && {
-			die "ERR > No loop device found. Execution failed"
+			die "ERR (${FUNCNAME:-Unknown}) > No loop device found. Execution failed"
 		} || { 
 			echo "No loop device found. Trying to load module"
-			modprobe loop || die "ERR > No loop device found and module cant be load"
+			modprobe loop || die "ERR (${FUNCNAME:-Unknown}) > No loop device found and module cant be load"
 			find_loop true
 		}
 	}
@@ -161,7 +162,7 @@ find_loop () {
 
 are_you_root () {
 	[ ${EUID:=1000} -ne 0 ] && {
-		echo "ERR > Script only run as root" >&2
+		echo "ERR (${FUNCNAME:-Unknown}) > Script only run as root" >&2
 		exit 1
 	}
 }
@@ -170,7 +171,7 @@ are_you_root () {
 find_nbd () {
 	CALL_BACK=${1:-false}
 	[ -e "/proc/partitions" ] || \
-		die "ERR > \"/proc/partitions\" not found. Execution failed"
+		die "ERR (${FUNCNAME:-Unknown}) > \"/proc/partitions\" not found. Execution failed"
 	for device in $(find /dev/ -maxdepth 1 -iname nbd* -exec basename {} \; | sort) ; do
 		echo "looking for network block device ${device}"
 		grep ${device} /proc/partitions || {
@@ -180,10 +181,10 @@ find_nbd () {
 	done
 	[ -z "${_NBD}" ] && {
 		${CALL_BACK} && {
-			die "ERR > No free network block device found. Execution failed. Try modprobe nbd and run again."
+			die "ERR (${FUNCNAME:-Unknown}) > No free network block device found. Execution failed. Try modprobe nbd and run again."
 		} || {
 			echo "No nbd device found. Trying to nbd module"
-			modprobe nbd || die "ERR > No nbd device found and module cant be load"
+			modprobe nbd || die "ERR (${FUNCNAME:-Unknown}) > No nbd device found and module cant be load"
 			find_nbd true
 		}
 	}
@@ -203,7 +204,7 @@ check_requirements () {
 		}
 		done
 	[[ -z "${RETURN}" ]] || \
-		die "ERR > Requirement missing. Try \"-v\" for more informations"
+		die "ERR (${FUNCNAME:-Unknown}) > Requirement missing. Try \"-v\" for more informations"
 }
 
 # init output
@@ -234,7 +235,7 @@ size_converter () {
 		P|p)
 			size_converter $(( 1024 * ${1%[p|P]} ))t ;;
 		*)
-			die "ERR > in \"size_converter\" Unknown unit" ;;
+			die "ERR (${FUNCNAME:-Unknown}) > in \"size_converter\" Unknown unit" ;;
 	esac
 }
 
@@ -259,7 +260,7 @@ size2humain_readable () {
 			echo "${1}"
 			return 0 ;;
 		*)
-			die "ERR > in \"size2humain_readable\" Unknown unit" ;;
+			die "ERR (${FUNCNAME:-Unknown}) > in \"size2humain_readable\" Unknown unit" ;;
 	esac
 }
 
@@ -268,12 +269,12 @@ validate_partitions () {
 	declare -A mountpoints fstype
 	local _rest_size=$(size_converter ${SIZE})
 
-	echo "${FUNCNAME}: checking partitions schema"
+	echo "${FUNCNAME:-Unknown}: checking partitions schema"
 
 	for _line in "${_PARTITIONS[@]}" ; do
 		IFS=':' read -ra entry <<<"${_line}"
 		[[ -n "${_use_rest}" ]] && \
-			die "ERR > only the last partition can use the rest of disk"
+			die "ERR (${FUNCNAME:-Unknown}) > only the last partition can use the rest of disk"
 
 		entry[1]=$(echo "${entry[1]}" | sed -e 's/[[:blank:]]//g')
 		local _size=$(size_converter ${entry[1],,})
@@ -287,7 +288,9 @@ validate_partitions () {
 			entry[5]=0
 		} || {
 			${WARN:=true} && [[ ${entry[0],,} =~ ${REGEXP_APPROXIMATIVE_SWAP} ]] && {
-				echo -e "\n>>> Warning: partition name \"${entry[0]}\" is proch of \"sw\" or \"swap\". Did you meen \"swap\" ? <<<\n If needed, press Ctrl+c to exit and modify your partitions definitions.\n"
+				enable_output
+				echo -e "\n>>> Warning: partition name \"${entry[0]}\" is proch of \"sw\" or \"swap\". Did you meen \"swap\" ? <<<\n If needed, press Ctrl+c to exit and modify your partitions definitions.\n" >&2
+				init_out
 				sleep 10 
 			}
 
@@ -307,7 +310,7 @@ validate_partitions () {
 				: ${_PARTBOOT:=$(( ${#PARTSTABLE[*]} + 1 ))}
 
 			${mountpoints["${_mount_point}"]:=false} && \
-				die "ERR > \"${_mount_point}\" already defined." || \
+				die "ERR (${FUNCNAME:-Unknown}) > \"${_mount_point}\" already defined." || \
 				mountpoints["${_mount_point}"]=true
 		}
 
@@ -315,14 +318,18 @@ validate_partitions () {
 		[[ -z "${_size}" ]] && {
 			_use_rest=${#PARTSTABLE[*]}
 			${warn:=true} && [[ ${_rest_size} -le $(size_converter ${MINIMAL_SIZE}) ]] && {
-				echo -e "\n>>> Warning: Size of last partition is less than ${MINIMAL_SIZE} ($(size2humain_readable ${_rest_size})) ! <<<\n Press Ctrl+c to exit and modify your partitions definitions.\n"
+				[[ ${_rest_size} -le $(size_converter ${ERROR_MINIMAL_SIZE:=1M}) ]] && \
+					die "ERR (${FUNCNAME:-Unknown}) > All Partitions can't be contain in image size (set to ${_SIZE}, use '-s' to change image size)."
+				enable_output
+				echo -e "\n>>> Warning: Size of last partition is less than ${MINIMAL_SIZE} ($(size2humain_readable ${_rest_size})) ! <<<\n Press Ctrl+c to exit and modify your partitions definitions.\n" >&2
+				init_out
 				sleep 10
 			}
 		} || {
 			(( _rest_size = _rest_size - _size ))
 
 			[[ ${_rest_size} -ge 0 ]] || \
-				die "ERR > Image size can't contain all partitions."
+				die "ERR (${FUNCNAME:-Unknown}) > Image size (set to ${_SIZE}) can't contain all partitions. Use '-s' to change image size."
 		}
 
 #	4 Check requirements
@@ -337,7 +344,7 @@ validate_partitions () {
 	done
 
 	[[ ! ${mountpoints["/"]} ]] && \
-		die "ERR > No \"/\" defined ! Bad partition schema."
+		die "ERR (${FUNCNAME:-Unknown}) > No \"/\" defined ! Bad partition schema."
 
 	unset mountpoints
 
@@ -390,7 +397,7 @@ init_env () {
 	case ${_ARCH} in
 		amd64)	KARCH=${_ARCH} ;;
 		i386) 	KARCH="686-pae" ;;
-		*)	die "ERR > Architecture unknown." ;;
+		*)	die "ERR (${FUNCNAME:-Unknown}) > Architecture unknown." ;;
 	esac
 	: ${_KERNEL:=${CMD_KERNEL:=${KERNEL}${KARCH}}}
 	echo "install kernel : ${_KERNEL}"
@@ -422,7 +429,7 @@ secure_tmout () {
 create_vm_hd () {
 	echo "create vm hard drive ${HD_IMG} (format ${_FORMAT})"
 	qemu-img create -f ${_FORMAT} "${HD_IMG}" ${_SIZE} || \
-		die "ERR > making ${HD_IMG} failed. Execution failed"
+		die "ERR (${FUNCNAME:-Unknown}) > making ${HD_IMG} failed. Execution failed"
 	echo "hard drive created"
 	secure_tmout
 }
@@ -431,7 +438,7 @@ hd2nbd () {
 	HD_FULL_PATH=$(dirname "$(readlink -f "${HD_IMG}")")/$(basename "${HD_IMG}")
 	echo "associate vm hd (${HD_FULL_PATH}) to nbd (${_NBD})"
 	qemu-nbd -c ${_NBD} "${HD_FULL_PATH}" || \
-		die "ERR > association ${_NBD} to ${HD_IMG} failed. Execution failed"
+		die "ERR (${FUNCNAME:-Unknown}) > association ${_NBD} to ${HD_IMG} failed. Execution failed"
 	STEPS[${#STEPS[@]}]="free_nbd"
 	echo "association ok"
 	secure_tmout
@@ -441,7 +448,7 @@ free_nbd () {
 	echo "freeing nbd ${_NBD}"
 	qemu-nbd -d ${_NBD} || {
 		unset STEPS[${#STEPS[@]}-1]
-		Kill "ERR > ${_NBD} wont be free."
+		Kill "ERR (${FUNCNAME:-Unknown}) > ${_NBD} wont be free."
 	}
 	echo "Freeing nbd ${_NBD} ok"
 	secure_tmout
@@ -454,14 +461,14 @@ end_of_script () {
 
 cleaning () {
 	while [ ${#STEPS[@]} -gt 0 ] ; do
-		echo "${FUNCNAME}: ${STEPS[${#STEPS[@]}-1]}"
+		echo "${FUNCNAME:-Unknown}: ${STEPS[${#STEPS[@]}-1]}"
 		${STEPS[${#STEPS[@]}-1]}
 		unset STEPS[${#STEPS[@]}-1]
 	done
-	echo "delete temporary mount point (if needed)"
+	echo "${FUNCNAME:-Unknown}: delete temporary mount point (if needed)"
 	[ -d "${_MOUNT_POINT}" ] && {
 		grep "${_MOUNT_POINT}" /proc/mounts && {
-			die "ERR > mount point \"${_MOUNT_POINT}\" still in use. Script cant erase it."
+			die "ERR (${FUNCNAME:-Unknown}) > mount point \"${_MOUNT_POINT}\" still in use. Script cant erase it."
 		} || {
 			rm -rf "${_MOUNT_POINT}"
 		}
@@ -469,12 +476,12 @@ cleaning () {
 }
 
 partitiondrive () {
-	echo "${FUNCNAME}: create partitions on ${_NBD} :"
+	echo "${FUNCNAME:-Unknown}: create partitions on ${_NBD} :"
 	_cmd=""
 	for _entry in ${PARTSTABLE[@]} ; do
 		IFS=':' read -ra _line <<<${_entry}
 		${_LOGIC} && [[ ${_line[1]} -eq 4 ]] && {
-			_cmd="${_cmd} mkpart extended ${_point:?ERR > Partitions errors} -1 "
+			_cmd="${_cmd} mkpart extended ${_point:?ERR (${FUNCNAME:-Unknown}) > Partitions errors} -1 "
 			(( _point = _point + 1 ))
 		}
 		[[ ${_line[4]} =~ ${REGEXP_SWAP} ]] && _line[4]=linux-swap || _line[4]=ext2
@@ -488,11 +495,11 @@ partitiondrive () {
 	
 	echo "executing : parted -s -a none ${_NBD} mklabel msdos unit KiB -- ${_cmd} print"
 	parted -s -a none ${_NBD} mklabel msdos unit KiB -- ${_cmd} print || \
-		die "ERR > Partitioning ${_NBD} Failed !"
+		die "ERR (${FUNCNAME:-Unknown}) > Partitioning ${_NBD} Failed !"
 }
 
 generatefstab () {
-	echo "${FUNCNAME}: generate fstab"
+	echo "${FUNCNAME:-Unknown}: generate fstab"
 	local _basedevice=/dev/sda
 	local _fstab=/etc/fstab
 	echo "# <file system>	<dir>	<type>	<options>	<dump>	<pass>" | tee "${_MOUNT_POINT}${_fstab}"
@@ -505,29 +512,29 @@ generatefstab () {
 		echo -ne "$(blkid -s UUID /dev/mapper/$(basename ${_NBD})p${line[1]} | sed 's/.*\(UUID=\"[^"]*\"\).*/\1/g')\t" | tee -a "${_MOUNT_POINT}${_fstab}"
 		echo -e "${line[2]// /\\ }\t${line[4]}\t${line[5]}\t${line[6]}\t${line[7]}" | tee -a "${_MOUNT_POINT}${_fstab}"
 	done
-	echo "${FUNCNAME}: fstab has been generated"
+	echo "${FUNCNAME:-Unknown}: fstab has been generated"
 }
 
 detect_partitions () {
-	echo "${FUNCNAME}: detecting partitions"
+	echo "${FUNCNAME:-Unknown}: detecting partitions"
 	kpartx -av ${_NBD} || \
-		die "ERR > partitions detection failed. Exit."
+		die "ERR (${FUNCNAME:-Unknown}) > partitions detection failed. Exit."
 	STEPS[${#STEPS[@]}]="free_part"
-	echo "${FUNCNAME}: partitions detected"
+	echo "${FUNCNAME:-Unknown}: partitions detected"
 	secure_tmout
 }
 
 free_part () {
-	echo "${FUNCNAME}: freeing partitions schema"
+	echo "${FUNCNAME:-Unknown}: freeing partitions schema"
 	kpartx -dv ${_NBD} || {
-		Kill "ERR > partitions wont be free. Exit."
+		Kill "ERR (${FUNCNAME:-Unknown}) > partitions wont be free. Exit."
 	}
-	echo "${FUNCNAME}: cleaning partitions ok"
+	echo "${FUNCNAME:-Unknown}: cleaning partitions ok"
 	secure_tmout
 }
 
 create_filesystem () {
-	echo "${FUNCNAME}: create filesystems"
+	echo "${FUNCNAME:-Unknown}: create filesystems"
 	for _entry in ${PARTSTABLE[@]} ; do
 		IFS=':' read -ra _line <<<${_entry}
 		${_LOGIC} && [[ ${_line[1]} -ge 4 ]] && (( _line[1] =  _line[1] + 1 ))
@@ -536,7 +543,7 @@ create_filesystem () {
 			_cmd=mkfs.${_line[4]//[[:blank:]]/}
 		echo -e ".${_cmd} /dev/mapper/$(basename ${_NBD})p${_line[1]}"
 		${_cmd} /dev/mapper/$(basename ${_NBD})p${_line[1]} || \
-			die "ERR > partition ${_NBD}p${_line[1]} can't be formated. Exit."
+			die "ERR (${FUNCNAME:-Unknown}) > partition ${_NBD}p${_line[1]} can't be formated. Exit."
 	done
 #	This waiting time is needed ...
 	sleep 1
@@ -545,12 +552,12 @@ create_filesystem () {
 create_tempdir () {
 	_MOUNT_POINT="$(mktemp -p "${_TMPDIR}" -d)"
 	[ -z "${_MOUNT_POINT}" ] && \
-		die "ERR > Mount point not create. Exit"
+		die "ERR (${FUNCNAME:-Unknown}) > Mount point not create. Exit"
 	echo "mount point created : ${_MOUNT_POINT}"
 }
 
 mountfs () {
-	echo "${FUNCNAME}: mounting filesystems"
+	echo "${FUNCNAME:-Unknown}: mounting filesystems"
  	STEPS[${#STEPS[@]}]="umountfs"
 	for _entry in ${ORDER_TABLE[@]} ; do
 		IFS=':' read -ra _line <<<${_entry}
@@ -560,44 +567,44 @@ mountfs () {
 		[[ ${_line[0]} -gt 1 ]] && {
 			echo "mkdir -p ${_MOUNT_POINT}/${_line[2]// /\\ }"
 			mkdir -p "${_MOUNT_POINT}/${_line[2]}" || \
-				die "ERR > Couldn't create directory"
+				die "ERR (${FUNCNAME:-Unknown}) > Couldn't create directory"
 		}
 		[[ ${_line[1]} -eq ${_PARTBOOT} ]] && {
 			echo "assosiate boot partition to loop device"
 			losetup ${_LOOP} /dev/mapper/$(basename ${_NBD})p${_line[1]} || \
-				die "ERR > associate first partition to loop device failed. Exit."
+				die "ERR (${FUNCNAME:-Unknown}) > associate first partition to loop device failed. Exit."
 			_device=${_LOOP}
 		}
 		echo "mount ${_device:=/dev/mapper/$(basename ${_NBD})p${_line[1]}} ${_MOUNT_POINT}${_line[2]// /\\ }"
 		mount "${_device:=/dev/mapper/$(basename ${_NBD})p${_line[1]}}" "${_MOUNT_POINT}${_line[2]}" && \
 			MONTEDPARTS[${#MONTEDPARTS[*]}]="${_device:=/dev/mapper/$(basename ${_NBD})p${_line[1]}}" || \
-			die "ERR > Failed to mount ${_device:=/dev/mapper/$(basename ${_NBD})p${_line[1]}} in \"${_MOUNT_POINT}\". Exit."
+			die "ERR (${FUNCNAME:-Unknown}) > Failed to mount ${_device:=/dev/mapper/$(basename ${_NBD})p${_line[1]}} in \"${_MOUNT_POINT}\". Exit."
 		unset _device
 	done
- 	echo "${FUNCNAME}: filesystems monted"
+ 	echo "${FUNCNAME:-Unknown}: filesystems monted"
 }
 
 umountfs () {
-		echo "${FUNCNAME}: umounting filesystems"
+		echo "${FUNCNAME:-Unknown}: umounting filesystems"
 		for _nbr in $(seq $(( ${#MONTEDPARTS[@]} -1)) -1 0) ; do
 			echo "umount \"${MONTEDPARTS[${_nbr}]}\""
 			umount ${MONTEDPARTS[${_nbr}]} || \
-				Kill "ERR > partition \"${MONTEDPARTS[${_nbr}]}\" still monted. Hard exit !"
+				Kill "ERR (${FUNCNAME:-Unknown}) > partition \"${MONTEDPARTS[${_nbr}]}\" still monted. Hard exit !"
 			[[ "${MONTEDPARTS[${_nbr}]}" == "${_LOOP}" ]] && {
 				echo "freeing loop device"
 				losetup -d "${_LOOP}" || \
-					Kill "ERR > Freeing loop device failed. Exit."
+					Kill "ERR (${FUNCNAME:-Unknown}) > Freeing loop device failed. Exit."
 				echo "freeing loop ok"
 				secure_tmout
 			}
 		done
-		echo "${FUNCNAME}: filesystems unmounted"
+		echo "${FUNCNAME:-Unknown}: filesystems unmounted"
 }
 
 install_sys () {
 	echo "debootstrap --arch=${_ARCH} --variant=minbase ${_VERSION} ${_MOUNT_POINT} ${_SERVER}"
 	debootstrap --arch=${_ARCH} --variant=minbase "${_VERSION}" "${_MOUNT_POINT}" "${_SERVER}" || {
-		die "ERR > installation failed. Exit."
+		die "ERR (${FUNCNAME:-Unknown}) > installation failed. Exit."
 	}
 }
 
@@ -615,38 +622,38 @@ __EOF__
 }
 
 mount_fs_dev () {
-	echo "${FUNCNAME}: mounting dev"
+	echo "${FUNCNAME:-Unknown}: mounting dev"
 	mount -o bind /dev/ "${_MOUNT_POINT}"/dev/ || {
-		die "ERR > failed to mount /dev in chroot"
+		die "ERR (${FUNCNAME:-Unknown}) > failed to mount /dev in chroot"
 	}
 	STEPS[${#STEPS[@]}]="umount_fs_dev"
-	echo "${FUNCNAME}: dev mounted"
+	echo "${FUNCNAME:-Unknown}: dev mounted"
 }
 
 umount_fs_dev () {
-	echo "${FUNCNAME}: unmounting dev"
+	echo "${FUNCNAME:-Unknown}: unmounting dev"
 	umount -l "${_MOUNT_POINT}"/dev/ || {
 		unset steps[${#steps[@]}-1]
-		kill "ERR > failed to umount /dev in chroot"
+		kill "ERR (${FUNCNAME:-Unknown}) > failed to umount /dev in chroot"
 	}
-	echo "${FUNCNAME}: dev unmounted"
+	echo "${FUNCNAME:-Unknown}: dev unmounted"
 }
 
 mount_fs_proc () {
-	echo "${FUNCNAME}: mounting proc"
+	echo "${FUNCNAME:-Unknown}: mounting proc"
 	mount -t proc proc "${_MOUNT_POINT}"/proc/ || \
-		die "ERR > failed to mount /proc in chroot"
+		die "ERR (${FUNCNAME:-Unknown}) > failed to mount /proc in chroot"
 	STEPS[${#STEPS[@]}]="umount_fs_proc"
-	echo "${FUNCNAME}: proc mounted"
+	echo "${FUNCNAME:-Unknown}: proc mounted"
 }
 
 umount_fs_proc () {
-	echo "${FUNCNAME}: unmounting proc"
+	echo "${FUNCNAME:-Unknown}: unmounting proc"
 	umount -l "${_MOUNT_POINT}"/proc/ || {
 		unset steps[${#steps[@]}-1]
-		kill "ERR > failed to umount /proc in chroot"
+		kill "ERR (${FUNCNAME:-Unknown}) > failed to umount /proc in chroot"
 	}
-	echo "${FUNCNAME}: proc unmounted"
+	echo "${FUNCNAME:-Unknown}: proc unmounted"
 }
 
 install_grub () {
@@ -656,13 +663,15 @@ source /etc/profile
 /usr/sbin/grub-install --no-floppy --boot-directory=/boot --modules="ext2 part_msdos" ${_NBD}
 __EOF__
 	[[ $? -gt 0 ]] && \
-		die "ERR > Installation of grub failed. Exit."
+		die "ERR (${FUNCNAME:-Unknown}) > Installation of grub failed. Exit."
 	chroot "${_MOUNT_POINT}" /bin/bash <<__EOF__
 source /etc/profile
 grub-mkconfig | grep -v ^[[:blank:]]loopback.* | grep -v "^[[:blank:]]set\ root=.*" > /boot/grub/grub.cfg
 __EOF__
 	[[ $? -gt 0 ]] && {
+		enable_output
 		echo ">>> Warning: Update grub2 failed ! <<<" >&2
+		init_out
 	}
 }
 
@@ -820,13 +829,15 @@ while getopts ":a:b:hc:vDn:f:k:s:S:p:V:A:t:l:Tio:P:" opt ; do
 			CMD_LISTPKG=${OPTARG} ;;
 		o)
 			echo "${OPTARG}" | grep [[:blank:]] > /dev/null && {
-				echo -e "> No space authorized in name of alternative temp dir (option \"-o\").\n"
+				echo -e "> No space authorized in name of alternative temp dir (option \"-o\").\n" >&2
 				usage
 			}
 			[ -d "${OPTARG}" -a -w "${OPTARG}" ] && {
 				_TMPDIR="${OPTARG%/}"
 			} || {
-				echo ">>> Warning: ${OPTARG} not a directory or not writable. Option ignored <<<"
+				enable_output
+				echo ">>> Warning: ${OPTARG} not a directory or not writable. Option ignored <<<" >&2
+				init_out
 			} ;;
 		p)
 			CMD_ROOTPWD="${OPTARG}" ;;
@@ -853,10 +864,10 @@ while getopts ":a:b:hc:vDn:f:k:s:S:p:V:A:t:l:Tio:P:" opt ; do
 		V)
 			CMD_VERSION=${OPTARG} ;;
 		:)
-			echo -e "> Option -$OPTARG requiert un argument.\n"
+			echo -e "> Option -$OPTARG requiert un argument.\n" >&2
 			usage ;;
 		*)
-			echo -e "> Invalide option \"-$OPTARG\".\n"
+			echo -e "> Invalide option \"-$OPTARG\".\n" >&2
 			usage ;;
 	esac
 done
@@ -868,7 +879,7 @@ case $# in
 	1)
 		HD_IMG="${1}" ;;
 	*)
-		echo -e "> Bad number of arguments\n\t${0} <hard drive image>\n"
+		echo -e "> Bad number of arguments\n\t${0} <hard drive image>\n" >&2
 		usage ;;
 esac
 
